version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - bodyclose
    - contextcheck
    - errorlint

formatters:
  enable:
    - gofmt
